# Generated by Django 5.0.1 on 2026-02-08 06:13

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('MEMBER_JOIN', 'Member Joins'), ('MEMBER_LEAVE', 'Member Leaves'), ('COMMAND', 'Bot Command'), ('FORM_SUBMIT', 'Form Submitted'), ('REACTION', 'Reaction Added')], max_length=20)),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='Filter conditions as JSON. Leave {} to match all events of this trigger type.')),
                ('admin_only', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'automations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'discord_channels',
            },
        ),
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'discord_roles',
            },
        ),
        migrations.CreateModel(
            name='GuildSettings',
            fields=[
                ('guild_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild_name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('AUTO', 'Auto'), ('APPROVAL', 'Approval')], default='AUTO', max_length=20)),
                ('bot_admin_role_id', models.BigIntegerField(blank=True, null=True)),
                ('pending_role_id', models.BigIntegerField(blank=True, null=True)),
                ('bounce_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('pending_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Guild Settings',
                'db_table': 'guild_settings',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('INSTALL_WELCOME', 'Installation Welcome'), ('JOIN_LOG_AUTO', 'Join Log (AUTO mode)'), ('JOIN_LOG_APPROVAL', 'Join Log (APPROVAL mode)'), ('PENDING_CHANNEL_TOPIC', 'Pending Channel – Topic (with form)'), ('PENDING_CHANNEL_TOPIC_NO_FORM', 'Pending Channel – Topic (no form)'), ('APPLICATION_SENT', 'Application Submitted'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('APPROVE_CONFIRM', 'Approve – Admin Confirmation'), ('APPROVE_DM', 'Approve – User DM'), ('REJECT_CONFIRM', 'Reject – Admin Confirmation'), ('REJECT_DM', 'Reject – User DM'), ('REJECT_PENDING', 'Reject – Pending Channel Notice'), ('APPROVAL_NOTIFICATION', 'Approval Channel Notification'), ('GETACCESS_RESPONSE', 'GetAccess Token Response'), ('GETACCESS_EXISTS', 'Token Already Exists'), ('GETACCESS_NO_ADMIN', 'GetAccess – Not Admin'), ('GETACCESS_PICK_SERVER', 'GetAccess – Pick Server'), ('HELP_MESSAGE', 'Help Command'), ('COMMAND_SUCCESS', 'Command Success'), ('COMMAND_ERROR', 'Command Error'), ('COMMAND_NOT_FOUND', 'Command Not Found'), ('DM_ONLY_WARNING', 'DM-Only Warning'), ('SERVER_ONLY_WARNING', 'Server-Only Warning'), ('SETUP_DIAGNOSTIC', 'Setup – Role Hierarchy Warning')], max_length=50, unique=True)),
                ('default_content', models.TextField()),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('action_type', models.CharField(choices=[('SEND_MESSAGE', 'Send Channel Message'), ('SEND_DM', 'Send DM'), ('SEND_EMBED', 'Send Embed'), ('ADD_ROLE', 'Add Role'), ('REMOVE_ROLE', 'Remove Role'), ('EDIT_MESSAGE', 'Edit Tracked Message'), ('SET_TOPIC', 'Set Channel Topic'), ('SET_PERMS', 'Grant Channel Access'), ('CLEANUP', 'Delete Old Bot Messages')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Parameters as JSON.  See Automation docs for format per action type.')),
                ('enabled', models.BooleanField(default=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.automation')),
            ],
            options={
                'db_table': 'actions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('ROLES', 'Guild Roles'), ('CHANNELS', 'Guild Channels'), ('CUSTOM', 'Custom Options')], max_length=20)),
                ('multiselect', models.BooleanField(default=False)),
                ('channels', models.ManyToManyField(blank=True, related_name='dropdowns', to='core.discordchannel')),
                ('roles', models.ManyToManyField(blank=True, related_name='dropdowns', to='core.discordrole')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdowns', to='core.guildsettings')),
            ],
            options={
                'db_table': 'dropdowns',
                'unique_together': {('guild', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('dropdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_options', to='core.dropdown')),
            ],
            options={
                'db_table': 'dropdown_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('dropdown', 'Dropdown'), ('checkbox', 'Yes/No Checkbox'), ('file', 'File Upload')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('dropdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dropdown')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='core.guildsettings')),
            ],
            options={
                'db_table': 'form_fields',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='discordrole',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.guildsettings'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.guildsettings'),
        ),
        migrations.AddField(
            model_name='automation',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='core.guildsettings'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=50)),
                ('inviter_id', models.BigIntegerField(blank=True, null=True)),
                ('inviter_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('responses', models.JSONField(default=dict)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_by', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.guildsettings')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guildsettings')),
            ],
            options={
                'db_table': 'access_tokens',
            },
        ),
        migrations.AlterUniqueTogether(
            name='discordrole',
            unique_together={('guild', 'discord_id')},
        ),
        migrations.AlterUniqueTogether(
            name='discordchannel',
            unique_together={('guild', 'discord_id')},
        ),
        migrations.AlterUniqueTogether(
            name='automation',
            unique_together={('guild', 'name')},
        ),
        migrations.CreateModel(
            name='InviteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.guildsettings')),
                ('roles', models.ManyToManyField(related_name='rules', to='core.discordrole')),
            ],
            options={
                'db_table': 'invite_rules',
                'unique_together': {('guild', 'invite_code')},
            },
        ),
        migrations.CreateModel(
            name='GuildMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_content', models.TextField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.guildsettings')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messagetemplate')),
            ],
            options={
                'db_table': 'guild_message_templates',
                'unique_together': {('guild', 'template')},
            },
        ),
    ]
