# Generated by Django 5.0.1 on 2026-02-08 04:26

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('core', '0001_initial'),
        ('core', '0002_reset_botcommand_table'),
        ('core', '0003_remove_discordchannel_is_deleted_and_more'),
        ('core', '0004_remove_botcommand_admin_only_and_more'),
        ('core', '0005_alter_commandaction_type'),
        ('core', '0006_add_pending_channel_id'),
        ('core', '0007_redesign_formfield_add_dropdowns'),
        ('core', '0008_dropdown_role_channel_selectors'),
        ('core', '0009_add_template_types'),
        ('core', '0010_update_pending_template_types'),
        ('core', '0011_add_reviewed_by_name_and_cleanup_approved'),
    ]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'discord_channels',
            },
        ),
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'discord_roles',
            },
        ),
        migrations.CreateModel(
            name='GuildSettings',
            fields=[
                ('guild_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild_name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('AUTO', 'Auto'), ('APPROVAL', 'Approval')], default='AUTO', max_length=20)),
                ('bot_admin_role_id', models.BigIntegerField(blank=True, null=True)),
                ('pending_role_id', models.BigIntegerField(blank=True, null=True)),
                ('logs_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('approvals_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('pending_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Guild Settings',
                'db_table': 'guild_settings',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('INSTALL_WELCOME', 'Installation Welcome'), ('JOIN_LOG_AUTO', 'Join Log (AUTO mode)'), ('JOIN_LOG_APPROVAL', 'Join Log (APPROVAL mode)'), ('PENDING_CHANNEL_TOPIC', 'Pending Channel – Topic (with form)'), ('PENDING_CHANNEL_TOPIC_NO_FORM', 'Pending Channel – Topic (no form)'), ('APPLICATION_SENT', 'Application Submitted'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('APPROVE_CONFIRM', 'Approve – Admin Confirmation'), ('APPROVE_DM', 'Approve – User DM'), ('REJECT_CONFIRM', 'Reject – Admin Confirmation'), ('REJECT_DM', 'Reject – User DM'), ('REJECT_PENDING', 'Reject – Pending Channel Notice'), ('APPROVAL_NOTIFICATION', 'Approval Channel Notification'), ('GETACCESS_RESPONSE', 'GetAccess Token Response'), ('GETACCESS_EXISTS', 'Token Already Exists'), ('GETACCESS_NO_ADMIN', 'GetAccess – Not Admin'), ('GETACCESS_PICK_SERVER', 'GetAccess – Pick Server'), ('HELP_MESSAGE', 'Help Command'), ('COMMAND_SUCCESS', 'Command Success'), ('COMMAND_ERROR', 'Command Error'), ('COMMAND_NOT_FOUND', 'Command Not Found'), ('COMMAND_DISABLED', 'Command Disabled'), ('DM_ONLY_WARNING', 'DM-Only Warning'), ('SERVER_ONLY_WARNING', 'Server-Only Warning'), ('SETUP_DIAGNOSTIC', 'Setup – Role Hierarchy Warning')], max_length=50, unique=True)),
                ('default_content', models.TextField()),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Role Picker', 'Region'", max_length=100)),
                ('source_type', models.CharField(choices=[('ROLES', 'Guild Roles'), ('CHANNELS', 'Guild Channels'), ('CUSTOM', 'Custom Options')], help_text='Where the options come from', max_length=20)),
                ('multiselect', models.BooleanField(default=False, help_text='Allow picking multiple options')),
                ('channels', models.ManyToManyField(blank=True, help_text="Select channels to include. Leave empty = ALL guild channels. Only used when source is 'Guild Channels'.", related_name='dropdowns', to='core.discordchannel')),
                ('roles', models.ManyToManyField(blank=True, help_text="Select roles to include. Leave empty = ALL guild roles. Only used when source is 'Guild Roles'.", related_name='dropdowns', to='core.discordrole')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdowns', to='core.guildsettings')),
            ],
            options={
                'db_table': 'dropdowns',
                'unique_together': {('guild', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What the user sees', max_length=200)),
                ('value', models.CharField(help_text='What gets stored (can match label)', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('dropdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_options', to='core.dropdown')),
            ],
            options={
                'db_table': 'dropdown_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Question shown to the user', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('dropdown', 'Dropdown (link a Dropdown below)'), ('checkbox', 'Yes/No Checkbox'), ('file', 'File Upload')], max_length=20)),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text shown inside text/textarea fields', max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('dropdown', models.ForeignKey(blank=True, help_text="Required for 'Dropdown' field type. Create one under Dropdowns first.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dropdown')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='core.guildsettings')),
            ],
            options={
                'db_table': 'form_fields',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='discordrole',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.guildsettings'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.guildsettings'),
        ),
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('enabled', models.BooleanField(default=True)),
                ('custom_name', models.CharField(blank=True, max_length=50)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.guildsettings')),
            ],
            options={
                'db_table': 'bot_commands',
                'unique_together': {('guild', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=50)),
                ('inviter_id', models.BigIntegerField(blank=True, null=True)),
                ('inviter_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('responses', models.JSONField()),
                ('reviewed_by', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.guildsettings')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guildsettings')),
            ],
            options={
                'db_table': 'access_tokens',
            },
        ),
        migrations.CreateModel(
            name='CommandAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('SEND_MESSAGE', 'Send Message'), ('ASSIGN_ROLE', 'Assign Role'), ('REMOVE_ROLE', 'Remove Role'), ('CREATE_CHANNEL', 'Create Channel'), ('DELETE_CHANNEL', 'Delete Channel'), ('POLL', 'Create Poll'), ('WEBHOOK', 'Call Webhook'), ('ADD_INVITE_RULE', 'Add Invite Rule'), ('DELETE_INVITE_RULE', 'Delete Invite Rule'), ('LIST_INVITE_RULES', 'List Invite Rules'), ('SET_SERVER_MODE', 'Set Server Mode'), ('LIST_COMMANDS', 'List Commands'), ('GENERATE_ACCESS_TOKEN', 'Generate Access Token'), ('LIST_FORM_FIELDS', 'List Form Fields'), ('RELOAD_CONFIG', 'Reload Configuration'), ('APPROVE_APPLICATION', 'Approve Application'), ('REJECT_APPLICATION', 'Reject Application')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict, help_text='Auto-managed by the bot. Only edit if you know what you\'re doing. Format depends on action type, e.g. {"text": "Hello"} for SEND_MESSAGE.')),
                ('enabled', models.BooleanField(default=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.botcommand')),
            ],
            options={
                'db_table': 'command_actions',
                'ordering': ['order'],
                'unique_together': {('command', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='discordrole',
            unique_together={('guild', 'discord_id')},
        ),
        migrations.AlterUniqueTogether(
            name='discordchannel',
            unique_together={('guild', 'discord_id')},
        ),
        migrations.CreateModel(
            name='InviteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.guildsettings')),
                ('roles', models.ManyToManyField(related_name='rules', to='core.discordrole')),
            ],
            options={
                'db_table': 'invite_rules',
                'unique_together': {('guild', 'invite_code')},
            },
        ),
        migrations.CreateModel(
            name='GuildMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_content', models.TextField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.guildsettings')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messagetemplate')),
            ],
            options={
                'db_table': 'guild_message_templates',
                'unique_together': {('guild', 'template')},
            },
        ),
    ]
