# Generated by Django 5.0 on 2026-02-06 14:59

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuildSettings',
            fields=[
                ('guild_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild_name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('AUTO', 'Auto'), ('APPROVAL', 'Approval')], default='AUTO', max_length=20)),
                ('bot_admin_role_id', models.BigIntegerField(blank=True, null=True)),
                ('pending_role_id', models.BigIntegerField(blank=True, null=True)),
                ('logs_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('approvals_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Guild Settings',
                'db_table': 'guild_settings',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('INSTALL_WELCOME', 'Installation Welcome'), ('JOIN_LOG_AUTO', 'Join Log (AUTO mode)'), ('JOIN_LOG_APPROVAL', 'Join Log (APPROVAL mode)'), ('APPLICATION_SENT', 'Application Submitted'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('APPROVAL_NOTIFICATION', 'Approval Channel Notification'), ('GETACCESS_RESPONSE', 'GetAccess Token Response'), ('GETACCESS_EXISTS', 'Token Already Exists'), ('HELP_MESSAGE', 'Help Command'), ('COMMAND_SUCCESS', 'Command Success'), ('COMMAND_ERROR', 'Command Error')], max_length=50, unique=True)),
                ('default_content', models.TextField()),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('file', 'File Upload')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='core.guildsettings')),
            ],
            options={
                'db_table': 'form_fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.guildsettings')),
            ],
            options={
                'db_table': 'discord_roles',
                'unique_together': {('guild', 'discord_id')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=50)),
                ('inviter_id', models.BigIntegerField(blank=True, null=True)),
                ('inviter_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('responses', models.JSONField()),
                ('reviewed_by', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.guildsettings')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guildsettings')),
            ],
            options={
                'db_table': 'access_tokens',
            },
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.guildsettings')),
            ],
            options={
                'db_table': 'discord_channels',
                'unique_together': {('guild', 'discord_id')},
            },
        ),
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('handler_function', models.CharField(default='', max_length=100)),
                ('admin_only', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('custom_name', models.CharField(blank=True, max_length=50)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='allowed_commands', to='core.discordrole')),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.guildsettings')),
            ],
            options={
                'db_table': 'bot_commands',
                'unique_together': {('guild', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InviteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.guildsettings')),
                ('roles', models.ManyToManyField(related_name='rules', to='core.discordrole')),
            ],
            options={
                'db_table': 'invite_rules',
                'unique_together': {('guild', 'invite_code')},
            },
        ),
        migrations.CreateModel(
            name='GuildMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_content', models.TextField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.guildsettings')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messagetemplate')),
            ],
            options={
                'db_table': 'guild_message_templates',
                'unique_together': {('guild', 'template')},
            },
        ),
    ]
