# Generated by Django 5.0 on 2026-02-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reset_botcommand_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordchannel',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='discordchannel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='discordrole',
            name='is_deleted',
        ),
    ]
