# Generated by Django 5.0 on 2026-02-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_discordchannel_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botcommand',
            name='admin_only',
        ),
        migrations.RemoveField(
            model_name='botcommand',
            name='allowed_roles',
        ),
        migrations.RemoveField(
            model_name='botcommand',
            name='handler_function',
        ),
        migrations.AlterField(
            model_name='botcommand',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CommandAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('SEND_MESSAGE', 'Send Message'), ('ASSIGN_ROLE', 'Assign Role'), ('REMOVE_ROLE', 'Remove Role'), ('CREATE_CHANNEL', 'Create Channel'), ('DELETE_CHANNEL', 'Delete Channel'), ('POLL', 'Create Poll'), ('WEBHOOK', 'Call Webhook')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.botcommand')),
            ],
            options={
                'db_table': 'command_actions',
                'ordering': ['order'],
                'unique_together': {('command', 'name')},
            },
        ),
    ]
