# Generated by Django 5.0 on 2026-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_botcommand_admin_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandaction',
            name='type',
            field=models.CharField(choices=[('SEND_MESSAGE', 'Send Message'), ('ASSIGN_ROLE', 'Assign Role'), ('REMOVE_ROLE', 'Remove Role'), ('CREATE_CHANNEL', 'Create Channel'), ('DELETE_CHANNEL', 'Delete Channel'), ('POLL', 'Create Poll'), ('WEBHOOK', 'Call Webhook'), ('ADD_INVITE_RULE', 'Add Invite Rule'), ('DELETE_INVITE_RULE', 'Delete Invite Rule'), ('LIST_INVITE_RULES', 'List Invite Rules'), ('SET_SERVER_MODE', 'Set Server Mode'), ('LIST_COMMANDS', 'List Commands'), ('GENERATE_ACCESS_TOKEN', 'Generate Access Token'), ('ADD_FORM_FIELD', 'Add Form Field'), ('LIST_FORM_FIELDS', 'List Form Fields'), ('RELOAD_CONFIG', 'Reload Configuration')], max_length=30),
        ),
    ]
