# Generated by Django 5.0.1 on 2026-02-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_commandaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='pending_channel_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandaction',
            name='type',
            field=models.CharField(choices=[('SEND_MESSAGE', 'Send Message'), ('ASSIGN_ROLE', 'Assign Role'), ('REMOVE_ROLE', 'Remove Role'), ('CREATE_CHANNEL', 'Create Channel'), ('DELETE_CHANNEL', 'Delete Channel'), ('POLL', 'Create Poll'), ('WEBHOOK', 'Call Webhook'), ('ADD_INVITE_RULE', 'Add Invite Rule'), ('DELETE_INVITE_RULE', 'Delete Invite Rule'), ('LIST_INVITE_RULES', 'List Invite Rules'), ('SET_SERVER_MODE', 'Set Server Mode'), ('LIST_COMMANDS', 'List Commands'), ('GENERATE_ACCESS_TOKEN', 'Generate Access Token'), ('LIST_FORM_FIELDS', 'List Form Fields'), ('RELOAD_CONFIG', 'Reload Configuration'), ('APPROVE_APPLICATION', 'Approve Application'), ('REJECT_APPLICATION', 'Reject Application')], max_length=30),
        ),
    ]
