# Generated by Django 5.0.1 on 2026-02-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_pending_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='options',
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text shown inside text/textarea fields', max_length=200),
        ),
        migrations.AlterField(
            model_name='commandaction',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Auto-managed by the bot. Only edit if you know what you\'re doing. Format depends on action type, e.g. {"text": "Hello"} for SEND_MESSAGE.'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('dropdown', 'Dropdown (link a Dropdown below)'), ('checkbox', 'Yes/No Checkbox'), ('file', 'File Upload')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(help_text='Question shown to the user', max_length=200),
        ),
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Role Picker', 'Region'", max_length=100)),
                ('source_type', models.CharField(choices=[('ROLES', 'Guild Roles'), ('CHANNELS', 'Guild Channels'), ('CUSTOM', 'Custom Options')], help_text='Where the options come from', max_length=20)),
                ('multiselect', models.BooleanField(default=False, help_text='Allow picking multiple options')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdowns', to='core.guildsettings')),
            ],
            options={
                'db_table': 'dropdowns',
                'unique_together': {('guild', 'name')},
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='dropdown',
            field=models.ForeignKey(blank=True, help_text="Required for 'Dropdown' field type. Create one under Dropdowns first.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dropdown'),
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What the user sees', max_length=200)),
                ('value', models.CharField(help_text='What gets stored (can match label)', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('dropdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_options', to='core.dropdown')),
            ],
            options={
                'db_table': 'dropdown_options',
                'ordering': ['order'],
            },
        ),
    ]
