# Generated by Django 5.0.1 on 2026-02-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_redesign_formfield_add_dropdowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdown',
            name='channels',
            field=models.ManyToManyField(blank=True, help_text="Select channels to include. Leave empty = ALL guild channels. Only used when source is 'Guild Channels'.", related_name='dropdowns', to='core.discordchannel'),
        ),
        migrations.AddField(
            model_name='dropdown',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text="Select roles to include. Leave empty = ALL guild roles. Only used when source is 'Guild Roles'.", related_name='dropdowns', to='core.discordrole'),
        ),
    ]
