# Generated by Django 5.0.1 on 2026-02-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dropdown_role_channel_selectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='template_type',
            field=models.CharField(choices=[('INSTALL_WELCOME', 'Installation Welcome'), ('JOIN_LOG_AUTO', 'Join Log (AUTO mode)'), ('JOIN_LOG_APPROVAL', 'Join Log (APPROVAL mode)'), ('PENDING_WELCOME', 'Pending Channel – Welcome (form link)'), ('PENDING_WELCOME_NO_FORM', 'Pending Channel – Welcome (no form)'), ('APPLICATION_SENT', 'Application Submitted'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('APPROVE_CONFIRM', 'Approve – Admin Confirmation'), ('APPROVE_DM', 'Approve – User DM'), ('REJECT_CONFIRM', 'Reject – Admin Confirmation'), ('REJECT_DM', 'Reject – User DM'), ('REJECT_PENDING', 'Reject – Pending Channel Notice'), ('APPROVAL_NOTIFICATION', 'Approval Channel Notification'), ('GETACCESS_RESPONSE', 'GetAccess Token Response'), ('GETACCESS_EXISTS', 'Token Already Exists'), ('GETACCESS_NO_ADMIN', 'GetAccess – Not Admin'), ('GETACCESS_PICK_SERVER', 'GetAccess – Pick Server'), ('HELP_MESSAGE', 'Help Command'), ('COMMAND_SUCCESS', 'Command Success'), ('COMMAND_ERROR', 'Command Error'), ('COMMAND_NOT_FOUND', 'Command Not Found'), ('COMMAND_DISABLED', 'Command Disabled'), ('DM_ONLY_WARNING', 'DM-Only Warning'), ('SERVER_ONLY_WARNING', 'Server-Only Warning'), ('SETUP_DIAGNOSTIC', 'Setup – Role Hierarchy Warning')], max_length=50, unique=True),
        ),
    ]
