# Generated by Django 5.0.1 on 2026-02-07 10:30

from django.db import migrations, models


def delete_approved_applications(apps, schema_editor):
    """Delete all approved applications from the database"""
    Application = apps.get_model('core', 'Application')
    Application.objects.filter(status='APPROVED').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_pending_template_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reviewed_by_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(delete_approved_applications),
    ]
